### PR TITLE
Add Github action and License badge

### PR DESCRIPTION
**Pull request by DannyFeliz**

### CODE REVIEW

**Review by carlospgraciano — APPROVED** [review]

**Comment by carlospgraciano** [comment]
Thanks, @DannyFeliz for this contribution.

Badges are used to display--to whoever enters our repository--the current state of the project which helps them to know if it's usable or not. It's a great tool to formalize Mantra as a usable project by the community.

I've approved these changes because I see value to Mantra but also @jonatangerman must check these changes and give the green light on this.

Hoping this change is merged!

**Review by jonatangerman — APPROVED** [review]
Totally agreed with the Github and License badge addition, certainly it gives a whole new formal level to the repository! Thanks a lot!

**Comment by DannyFeliz** [comment]
@carlospgraciano @jonatangerman So :eyes: ?

**Comment by carlospgraciano** [comment]
> @carlospgraciano @jonatangerman So 👀 ?

What if we close this PR and create another PR like this from your forked version into Mantra Develop branch. Could you do it? @DannyFeliz 

As of now, we still don't know what's happening with the status checks of `DEP` and `YAMBURGER`.

**Comment by DannyFeliz** [comment]
Are you guys using those integrations? If the answer is no then just remove them.

**Comment by jonatangerman** [comment]
Actually a good suggestion, since we are not using those integrations, lets remove them from the repo. Thanks! Sr. @DannyFeliz

**Pull request merged**
